// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgUqekfaRm6ukqMZVoiq6lsowKTmkapb8',
    appId: '1:843012205767:web:20f51463b733179013a2e2',
    messagingSenderId: '843012205767',
    projectId: 'pdm-fatec-1',
    authDomain: 'pdm-fatec-1.firebaseapp.com',
    storageBucket: 'pdm-fatec-1.firebasestorage.app',
    measurementId: 'G-4LSK9TS5ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8qNm3IDEcgjGUK6v3uhkpif_FFylCVJA',
    appId: '1:843012205767:android:d82dc7e7f7dbdf9313a2e2',
    messagingSenderId: '843012205767',
    projectId: 'pdm-fatec-1',
    storageBucket: 'pdm-fatec-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJnC8PZmczKRX00d2b54UioX8pq3sXPU',
    appId: '1:843012205767:ios:cc0fa3928cc7e6e213a2e2',
    messagingSenderId: '843012205767',
    projectId: 'pdm-fatec-1',
    storageBucket: 'pdm-fatec-1.firebasestorage.app',
    iosBundleId: 'com.example.pdmFatec1',
  );
}
